### ISSUE TITLE
fetch-git: Add option to disable debug traces

### ISSUE THREAD

**Issue by shlevy** [target/nix-fetchers#10]
Since debug lines are passed through to the output, there should be a way to call fetch-git without them being printed, relying on the caller to print them or not as needed.

**Comment by grahamc** [comment]
How would you expect the caller to print them or not print them?

**Comment by grahamc** [comment]
How would you expect the caller to print them or not print them?

**Comment by shlevy** [comment]
https://github.com/shlevy/source-specifications/blob/aafb35d070ba5cec72fbf281ae785310150d0820/src/default.nix#L247-L276 for example
