### ISSUE TITLE
fetch-git:  Warn users when about to do a full fetch of a massive repo

### ISSUE THREAD

**Issue by shlevy** [target/nix-fetchers#3]
An initial fetch of a massive repo currently causes a big pause, would be good to have a notice up-front that this is expected.

**Comment by dtzWill** [comment]
Bonus points for progress bar or something :P.

Although iirc improvement over nix builtin would be had by simply informing user fetchGit was underway-- regardless of size/pause. Not sure if this does that already, but if not might be low-hanging fruit.

(Might be straightforward to add to Nix too, not sure)

**Comment by grahamc** [comment]
Yes, maybe just emitting `Fetching XYZRepo @ branch/rev/tag` would be a good place to start?
