### ISSUE TITLE
fetchGit revision without branch

### ISSUE THREAD

**Issue by bobvanderlinden** [target/nix-fetchers#5]
It would be nice to fetch a single revision without specifying a branch. Would that be a viable option or is there something that requires the branch to be specified?

For example:
```
fetch-git {
  url = "https://github.com/nixos/nixpkgs.git";
  revision = "8bf6df2b8e8fc9e2f012901af48214feff918d9d";
}
```

**Comment by shlevy** [comment]
@bobvanderlinden We could default the branch to `master` (or whatever the upstream repo sets as its default ref), but fundamentally the git APIs do not in general allow you to directly fetch a rev, so you need to know which ref to look under to find the rev in question (or to do a full clone of all refs, which is expensive and rarely what you want. Maybe we could enable that under a flag).

**Comment by bobvanderlinden** [comment]
Ah, I get what you're saying. For `fetch-git` I understand and close this one.

For a potential future `fetchFromGitHub` it might make sense to allow (or require?) specifying a revision, which will be fetched using the archive API. Would that be a viable addition?

**Comment by grahamc** [comment]
I believe so, this would be especially helpful for fetching nixpkgs, since fetching nixpkgs will almost always require an initial full cloning of the repository.

**Comment by shlevy** [comment]
Should this be a transparent optimization of fetch-git? It's not like it's hard to figure out that the repo is being fetched from github.

**Comment by bobvanderlinden** [comment]
I like the way `fetchFromGitHub` works in that you explicitly state that it is fetching from GitHub and in turn uses fetchUrl. It would still be nice to have a `fetchFromGitHub` version that does not require a SHA256 when a revision is supplied.
